// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onLedChange();
void onScheduleChange();
void onDeleteLastFloodAlertButtonChange();
void onFloodAlertButtonChange();

CloudLight led;
CloudTemperatureSensor temperature;
CloudRelativeHumidity humidity;
CloudSchedule schedule;
bool deleteLastFloodAlertButton;
bool floodAlertButton;

void initProperties(){

  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(schedule, READWRITE, ON_CHANGE, onScheduleChange);
  ArduinoCloud.addProperty(deleteLastFloodAlertButton, READWRITE, ON_CHANGE, onDeleteLastFloodAlertButtonChange);
  ArduinoCloud.addProperty(floodAlertButton, READWRITE, ON_CHANGE, onFloodAlertButtonChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
